# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=files.models.upload_to)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
