# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170124_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang_code',
            field=models.CharField(default='zh-hans', max_length=10),
            preserve_default=False,
        ),
    ]
