# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 11:18
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170209_2304'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('lang_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
