# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170124_2330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reply',
            new_name='Comment',
        ),
    ]
