# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_mentions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('can_verify', 'Can verify')]},
        ),
    ]
