# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20170130_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lang_code',
            field=models.CharField(default='zh-hans', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when=set(['verified'])),
        ),
    ]
