# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20170202_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-published', '-edited'), 'permissions': [('can_verify', 'Can verify')]},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-posted',)},
        ),
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
    ]
