# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='lang_code',
            field=models.CharField(default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='lang_code',
            field=models.CharField(default='all', max_length=10),
        ),
    ]
