# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20170214_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_article',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
