# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20170218_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-published', '-edited'), 'permissions': [('can_verify', 'Can verify')], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterField(
            model_name='article',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='files.Attachment', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='edited',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='content', verbose_name='编辑时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_article',
            field=models.BooleanField(verbose_name='是文章'),
        ),
        migrations.AlterField(
            model_name='article',
            name='lang_code',
            field=models.CharField(choices=[('en-us', '英文'), ('zh-hans', '中文'), ('all', '全部')], default='all', max_length=10, verbose_name='语言标识'),
        ),
        migrations.AlterField(
            model_name='article',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_articles', to=settings.AUTH_USER_MODEL, verbose_name='@我的'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='发布时间', when=set(['verified'])),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='pending', max_length=100, no_check_for_status=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='lang_code',
            field=models.CharField(choices=[('en-us', '英文'), ('zh-hans', '中文'), ('all', '全部')], default='all', max_length=10, verbose_name='语言标识'),
        ),
    ]
