# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='action',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='actor',
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
