# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170205_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='group_name',
            new_name='session_name',
        ),
    ]
