# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20170205_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uid',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='files.Attachment'),
        ),
    ]
